"""Generate an HTML summary of all FP16 baseline experiments."""
import json
from pathlib import Path

LOGS = Path("logs")

EXPERIMENTS = [
    {
        "file": "gsm8k_fp16_results.json",
        "model": "Mistral-7B-Instruct-v0.2",
        "task": "GSM8k (5-shot)",
        "key": "gsm8k",
    },
    {
        "file": "gsm8k_cot_fp16_results.json",
        "model": "Mistral-7B-Instruct-v0.2",
        "task": "GSM8k CoT (8-shot)",
        "key": "gsm8k_cot",
    },
    {
        "file": "gsm8k_cot_zeroshot_fp16_results.json",
        "model": "Mistral-7B-Instruct-v0.2",
        "task": "GSM8k CoT (0-shot)",
        "key": "gsm8k_cot_zeroshot",
    },
    {
        "file": "gsm8k_llama-2-7b-chat-hf_fp16_results.json",
        "model": "Llama-2-7b-chat-hf",
        "task": "GSM8k (5-shot)",
        "key": "gsm8k",
    },
]


def load(exp):
    path = LOGS / exp["file"]
    if not path.exists():
        return None
    with open(path) as f:
        d = json.load(f)
    return d.get(exp["key"], {})


def pct(v):
    return f"{v * 100:.2f}%"


def build_html():
    rows = []
    for exp in EXPERIMENTS:
        data = load(exp)
        if data is None:
            continue
        strict = data.get("exact_match,strict-match")
        strict_se = data.get("exact_match_stderr,strict-match")
        flex = data.get("exact_match,flexible-extract")
        flex_se = data.get("exact_match_stderr,flexible-extract")
        rows.append({
            "model": exp["model"],
            "task": exp["task"],
            "strict": strict,
            "strict_se": strict_se,
            "flex": flex,
            "flex_se": flex_se,
        })

    tbody = ""
    for i, r in enumerate(rows):
        bg = "#f9f9ff" if i % 2 == 0 else "white"
        strict_str = f'{pct(r["strict"])} <span class="se">&plusmn;{pct(r["strict_se"])}</span>' if r["strict"] is not None else "—"
        flex_str = f'{pct(r["flex"])} <span class="se">&plusmn;{pct(r["flex_se"])}</span>' if r["flex"] is not None else "—"
        tbody += f"""
        <tr style="background:{bg}">
          <td>{r["model"]}</td>
          <td>{r["task"]}</td>
          <td class="num">{strict_str}</td>
          <td class="num">{flex_str}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>KIVI FP16 Baseline Results</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    max-width: 960px; margin: 40px auto; padding: 0 20px; color: #222;
  }}
  h1 {{ font-size: 1.5em; margin-bottom: 4px; }}
  p.sub {{ color: #666; font-size: 0.9em; margin-top: 0; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 20px; font-size: 0.92em; }}
  th {{
    background: #2c3e50; color: white; padding: 10px 14px; text-align: center;
  }}
  th.left {{ text-align: left; }}
  td {{ padding: 8px 14px; border-bottom: 1px solid #e0e0e0; }}
  td.num {{ text-align: center; font-variant-numeric: tabular-nums; }}
  .se {{ font-size: 0.78em; color: #888; }}
  tr:hover td {{ background: #eef3ff !important; }}
  .footer {{
    font-size: 0.8em; color: #888; margin-top: 16px;
    border-top: 1px solid #e0e0e0; padding-top: 12px;
  }}
</style>
</head>
<body>

<h1>KIVI — FP16 Baseline Results (No Quantization)</h1>
<p class="sub">
  All models evaluated in FP16 precision without KV cache quantization.<br>
  GSM8K: 1319 test questions &nbsp;|&nbsp; Greedy decoding
</p>

<table>
  <thead>
    <tr>
      <th class="left">Model</th>
      <th class="left">Task</th>
      <th>Strict Match</th>
      <th>Flexible Extract</th>
    </tr>
  </thead>
  <tbody>{tbody}
  </tbody>
</table>

<div class="footer">
  Hardware: NVIDIA A100-SXM4-80GB &nbsp;|&nbsp; batch_size=16 &nbsp;|&nbsp;
  Seeds: random=0, numpy=1234, torch=1234 &nbsp;|&nbsp;
  Generated by generate_summary.py
</div>

</body>
</html>"""
    return html


if __name__ == "__main__":
    html = build_html()
    out = "summary.html"
    with open(out, "w") as f:
        f.write(html)
    print(f"Written to {out}")
