"""Tests for SmoothKV calibration-variant generation logic.

The puremax and QK-based variants are generated by hand-rolled scripts that
have shown up multiple times in this repo (different files / different pods).
These tests pin down their math so a future refactor can't silently change
the formulas.
"""
import torch


def gen_puremax_variant(base: dict, alpha: float = 1.0, beta: float = 1.0,
                        eps: float = 1e-5, pair_max: bool = True) -> dict:
    """Reference puremax: s_K = max|K|^α (optionally pair-max), s_V = max|V|^β."""
    s_K = base["max_k"].clamp(min=eps) ** alpha
    s_V = base["max_v"].clamp(min=eps) ** beta
    if pair_max:
        L, nh, D = s_K.shape
        s_K = (s_K.view(L, nh, D // 2, 2)
                  .max(dim=-1, keepdim=True).values
                  .expand(L, nh, D // 2, 2)
                  .reshape(L, nh, D)
                  .clone())
    return {**base, "s_K": s_K, "s_V": s_V,
            "alpha": alpha, "beta": beta, "pair_max_k": pair_max}


def gen_qk_variant(base: dict, alpha: float, beta: float,
                   eps: float = 1e-5, pair_max: bool = True) -> dict:
    """Reference QK-based: s_K = max|K|^α / max|Q|^(1-α), s_V = max|V|^β.

    GQA: max_q has more heads than max_k; reduce Q across each KV-head group.
    """
    max_k = base["max_k"].clamp(min=eps)
    max_q = base["max_q"].clamp(min=eps)
    L, nh_q, D = max_q.shape
    _, nh_kv, _ = max_k.shape
    grp = nh_q // nh_kv
    max_q_grp = max_q.view(L, nh_kv, grp, D).max(dim=2).values   # (L, nh_kv, D)
    s_K = (max_k ** alpha) / (max_q_grp ** (1 - alpha))
    s_K = s_K.clamp(min=eps)
    if pair_max:
        s_K = (s_K.view(L, nh_kv, D // 2, 2)
                  .max(dim=-1, keepdim=True).values
                  .expand(L, nh_kv, D // 2, 2)
                  .reshape(L, nh_kv, D)
                  .clone())
    s_V = base["max_v"].clamp(min=eps) ** beta
    return {**base, "s_K": s_K, "s_V": s_V,
            "alpha": alpha, "beta": beta, "pair_max_k": pair_max,
            "scaling_method": "qk"}


def _mock_base(L=4, nh_kv=2, nh_q=8, D=64):
    torch.manual_seed(0)
    return {
        "max_k": torch.rand(L, nh_kv, D) + 0.1,
        "max_v": torch.rand(L, nh_kv, D) + 0.1,
        "max_q": torch.rand(L, nh_q, D) + 0.1,
    }


def test_puremax_alpha_one_equals_max_k():
    """At α=β=1, s_K should equal max_k (modulo pair-max)."""
    base = _mock_base()
    v = gen_puremax_variant(base, alpha=1.0, beta=1.0, pair_max=False)
    assert torch.allclose(v["s_K"], base["max_k"])
    assert torch.allclose(v["s_V"], base["max_v"])


def test_puremax_alpha_zero_returns_ones_after_clamp():
    """At α=0, s_K = (clamped max_k)^0 = 1.0 everywhere."""
    base = _mock_base()
    v = gen_puremax_variant(base, alpha=0.0, beta=0.0, pair_max=False)
    assert torch.allclose(v["s_K"], torch.ones_like(v["s_K"]))


def test_puremax_pair_max_invariant():
    """Adjacent-pair convention: s_K[..., 2d] == s_K[..., 2d+1]."""
    base = _mock_base()
    v = gen_puremax_variant(base, alpha=1.0, beta=1.0, pair_max=True)
    s_K = v["s_K"]
    assert torch.equal(s_K[..., 0::2], s_K[..., 1::2])


def test_qk_variant_shape_matches_kv_heads():
    """QK variant's s_K must reduce Q from nh_q heads to nh_kv heads."""
    base = _mock_base(nh_kv=2, nh_q=8)
    v = gen_qk_variant(base, alpha=0.75, beta=1.0)
    assert v["s_K"].shape == base["max_k"].shape
    assert v["s_K"].shape[1] == 2   # nh_kv, not 8


def test_qk_alpha_one_equals_puremax():
    """QK with α=1 reduces to puremax (max_q^0 = 1)."""
    base = _mock_base()
    qk = gen_qk_variant(base, alpha=1.0, beta=1.0, pair_max=False)
    pm = gen_puremax_variant(base, alpha=1.0, beta=1.0, pair_max=False)
    assert torch.allclose(qk["s_K"], pm["s_K"])


def test_clamp_eps_prevents_zero_division():
    """If max_k has zeros (e.g. dead channels), clamping prevents NaN/inf."""
    base = _mock_base()
    base["max_k"][0, 0, 0] = 0.0   # inject a dead channel
    v = gen_puremax_variant(base, alpha=1.0)
    assert torch.isfinite(v["s_K"]).all()
    assert (v["s_K"] > 0).all()
