task: gsm8k_32k_chat
dataset_path: openai/gsm8k
dataset_name: main
output_type: generate_until
training_split: train
fewshot_split: train
test_split: test
doc_to_text: "<|im_start|>user\n{{question}}\nPlease reason step by step, and put your final answer within \\boxed{}. /no_think<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"
doc_to_target: "{{answer}}"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: false
    regexes_to_ignore:
      - ","
      - "\\$"
      - "(?s).*#### "
      - "\\.$"
generation_kwargs:
  until:
    - "<|im_end|>"
    - "</s>"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 32768
repeats: 1
num_fewshot: 0
filter_list:
  - name: "strict-match"
    filter:
      - function: "regex"
        regex_pattern: "\\\\boxed\\{([^}]*)\\}"
      - function: "take_first"
  - name: "flexible-extract"
    filter:
      - function: "regex"
        group_select: -1
        regex_pattern: "(-?[$0-9.,]{2,})|(-?[0-9]+)"
      - function: "take_first"
metadata:
  version: 1.0
